//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disaster_information_viewer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70, 80, 100")]
        public global::System.Drawing.Color ShindoColor20 {
            get {
                return ((global::System.Drawing.Color)(this["ShindoColor20"]));
            }
            set {
                this["ShindoColor20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70, 100, 110")]
        public global::System.Drawing.Color ShindoColor21 {
            get {
                return ((global::System.Drawing.Color)(this["ShindoColor21"]));
            }
            set {
                this["ShindoColor21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30, 110, 230")]
        public global::System.Drawing.Color ShindoColor22 {
            get {
                return ((global::System.Drawing.Color)(this["ShindoColor22"]));
            }
            set {
                this["ShindoColor22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 200, 200")]
        public global::System.Drawing.Color ShindoColor23 {
            get {
                return ((global::System.Drawing.Color)(this["ShindoColor23"]));
            }
            set {
                this["ShindoColor23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250, 250, 100")]
        public global::System.Drawing.Color ShindoColor24 {
            get {
                return ((global::System.Drawing.Color)(this["ShindoColor24"]));
            }
            set {
                this["ShindoColor24"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 180, 0")]
        public global::System.Drawing.Color ShindoColor25 {
            get {
                return ((global::System.Drawing.Color)(this["ShindoColor25"]));
            }
            set {
                this["ShindoColor25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 120, 0")]
        public global::System.Drawing.Color ShindoColor26 {
            get {
                return ((global::System.Drawing.Color)(this["ShindoColor26"]));
            }
            set {
                this["ShindoColor26"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230, 0, 0")]
        public global::System.Drawing.Color ShindoColor27 {
            get {
                return ((global::System.Drawing.Color)(this["ShindoColor27"]));
            }
            set {
                this["ShindoColor27"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("160, 0, 0")]
        public global::System.Drawing.Color ShindoColor28 {
            get {
                return ((global::System.Drawing.Color)(this["ShindoColor28"]));
            }
            set {
                this["ShindoColor28"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150, 0, 150")]
        public global::System.Drawing.Color ShindoColor29 {
            get {
                return ((global::System.Drawing.Color)(this["ShindoColor29"]));
            }
            set {
                this["ShindoColor29"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ShindoColor30 {
            get {
                return ((global::System.Drawing.Color)(this["ShindoColor30"]));
            }
            set {
                this["ShindoColor30"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ShindoColor31 {
            get {
                return ((global::System.Drawing.Color)(this["ShindoColor31"]));
            }
            set {
                this["ShindoColor31"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ShindoColor32 {
            get {
                return ((global::System.Drawing.Color)(this["ShindoColor32"]));
            }
            set {
                this["ShindoColor32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30, 30, 60")]
        public global::System.Drawing.Color ShindoColor33 {
            get {
                return ((global::System.Drawing.Color)(this["ShindoColor33"]));
            }
            set {
                this["ShindoColor33"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30, 30, 60")]
        public global::System.Drawing.Color ShindoColor34 {
            get {
                return ((global::System.Drawing.Color)(this["ShindoColor34"]));
            }
            set {
                this["ShindoColor34"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30, 30, 60")]
        public global::System.Drawing.Color ShindoColor35 {
            get {
                return ((global::System.Drawing.Color)(this["ShindoColor35"]));
            }
            set {
                this["ShindoColor35"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30, 30, 60")]
        public global::System.Drawing.Color ShindoColor36 {
            get {
                return ((global::System.Drawing.Color)(this["ShindoColor36"]));
            }
            set {
                this["ShindoColor36"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ShindoColor37 {
            get {
                return ((global::System.Drawing.Color)(this["ShindoColor37"]));
            }
            set {
                this["ShindoColor37"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ShindoColor38 {
            get {
                return ((global::System.Drawing.Color)(this["ShindoColor38"]));
            }
            set {
                this["ShindoColor38"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ShindoColor39 {
            get {
                return ((global::System.Drawing.Color)(this["ShindoColor39"]));
            }
            set {
                this["ShindoColor39"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 50, 70")]
        public global::System.Drawing.Color ShindoColor10 {
            get {
                return ((global::System.Drawing.Color)(this["ShindoColor10"]));
            }
            set {
                this["ShindoColor10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 70, 80")]
        public global::System.Drawing.Color ShindoColor11 {
            get {
                return ((global::System.Drawing.Color)(this["ShindoColor11"]));
            }
            set {
                this["ShindoColor11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 80, 200")]
        public global::System.Drawing.Color ShindoColor12 {
            get {
                return ((global::System.Drawing.Color)(this["ShindoColor12"]));
            }
            set {
                this["ShindoColor12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 170, 170")]
        public global::System.Drawing.Color ShindoColor13 {
            get {
                return ((global::System.Drawing.Color)(this["ShindoColor13"]));
            }
            set {
                this["ShindoColor13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220, 220, 70")]
        public global::System.Drawing.Color ShindoColor14 {
            get {
                return ((global::System.Drawing.Color)(this["ShindoColor14"]));
            }
            set {
                this["ShindoColor14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("225, 150, 0")]
        public global::System.Drawing.Color ShindoColor15 {
            get {
                return ((global::System.Drawing.Color)(this["ShindoColor15"]));
            }
            set {
                this["ShindoColor15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("225, 90, 0")]
        public global::System.Drawing.Color ShindoColor16 {
            get {
                return ((global::System.Drawing.Color)(this["ShindoColor16"]));
            }
            set {
                this["ShindoColor16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 0, 0")]
        public global::System.Drawing.Color ShindoColor17 {
            get {
                return ((global::System.Drawing.Color)(this["ShindoColor17"]));
            }
            set {
                this["ShindoColor17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150, 0, 0")]
        public global::System.Drawing.Color ShindoColor18 {
            get {
                return ((global::System.Drawing.Color)(this["ShindoColor18"]));
            }
            set {
                this["ShindoColor18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("140, 0, 140")]
        public global::System.Drawing.Color ShindoColor19 {
            get {
                return ((global::System.Drawing.Color)(this["ShindoColor19"]));
            }
            set {
                this["ShindoColor19"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35.45")]
        public double UserLatitude {
            get {
                return ((double)(this["UserLatitude"]));
            }
            set {
                this["UserLatitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("136.75")]
        public double UserLongitude {
            get {
                return ((double)(this["UserLongitude"]));
            }
            set {
                this["UserLongitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("165")]
        public int UserPixelX {
            get {
                return ((int)(this["UserPixelX"]));
            }
            set {
                this["UserPixelX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("265")]
        public int UserPixelY {
            get {
                return ((int)(this["UserPixelY"]));
            }
            set {
                this["UserPixelY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Log_RemainingTimeComputation {
            get {
                return ((bool)(this["Log_RemainingTimeComputation"]));
            }
            set {
                this["Log_RemainingTimeComputation"] = value;
            }
        }
    }
}
